version: "2017-09-20"
pipeline:
  - id: build
    type: script
    vm_config: 
      type: linux
      image: cdp-runtime/python-3.9
    commands:
      - desc: Run tests
        cmd: |
          pip3 install -r requirements.txt 
          python3 setup.py test

      - desc: Build docker images for different architectures
        cmd: |
          IMAGE="container-registry-test.zalando.net/aruha/bubuku-appliance:oss-${CDP_BUILD_VERSION}"

          # create a Buildkit builder with CDP specific configuration
          docker buildx create \
                --config /etc/cdp-buildkitd.toml \
                --driver-opt network=host \
                --name cdpbuildx \
                --bootstrap \
                --use

          # (1) build image for AMD64 and ARM64 and push it to the Zalando Container Registry
          docker buildx build \
                --platform linux/amd64,linux/arm64 \
                -t ${IMAGE} \
                --push \
                .

          # (2) promote it from `container-registry-test` to `container-registry`, marking it production-ready
          cdp-promote-image ${IMAGE}

  - id: push-pierone-arm64
    type: script
    when:
      event: push
    vm_config:
      type: linux
      image: cdp-runtime/base
    commands:
      - desc: Push ARM64 image to PierOne
        cmd: |
          IMAGE="container-registry.zalando.net/aruha/bubuku-appliance:oss-${CDP_BUILD_VERSION}"
          PIERONE_IMAGE="registry-write.opensource.zalan.do/aruha/bubuku-appliance:oss-${CDP_BUILD_VERSION}-arm64"

          docker pull --platform linux/arm64 $IMAGE
          docker tag $IMAGE $PIERONE_IMAGE
          docker push $PIERONE_IMAGE

  - id: push-pierone-amd64
    type: script
    when:
      event: push
    vm_config:
      type: linux
      image: cdp-runtime/base
    commands:
      - desc: Push AMD64 image to PierOne
        cmd: |
          IMAGE="container-registry.zalando.net/aruha/bubuku-appliance:oss-${CDP_BUILD_VERSION}"
          PIERONE_IMAGE="registry-write.opensource.zalan.do/aruha/bubuku-appliance:oss-${CDP_BUILD_VERSION}-amd64"

          docker pull --platform linux/amd64 $IMAGE
          docker tag $IMAGE $PIERONE_IMAGE
          docker push $PIERONE_IMAGE

notifications:
  - channel: google_chat
    rooms:
      - AAAAmX_hkRQ
